#!/usr/bin/env python3
"""
Interactive setup wizard for Bigas local MVP.

Guides new users through the minimum configuration needed to run Bigas
locally with in-memory chat storage — no GCP, Firebase, or Discord required.

Usage:
    python scripts/setup.py
"""
from __future__ import annotations

import os
import sys
from datetime import datetime, timezone

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ENV_PATH = os.path.join(REPO_ROOT, ".env")

MVP_DEFAULTS = {
    "SECRET_MANAGER": "false",
    "FLASK_ENV": "development",
    "FLASK_DEBUG": "false",
    "PORT": "8080",
    "SERVER_URL": "http://localhost:8080",
    "CHAT_ENABLED": "true",
    "CHAT_STORAGE_MODE": "memory",
    "CHAT_AUTH_MODE": "dev",
    "CHAT_DEV_TOKEN": "bigas-dev-token",
}

LLM_MODELS = {
    "gemini": "gemini-3.1-pro-preview",
    "openai": "gpt-4o",
}


def _prompt(message: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    while True:
        try:
            value = input(f"{message}{suffix}: ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\nSetup cancelled.")
            sys.exit(1)
        if value:
            return value
        if default:
            return default
        print("  Please enter a value (or Ctrl+C to cancel).")


def _prompt_yes_no(message: str, default: bool = False) -> bool:
    hint = "Y/n" if default else "y/N"
    while True:
        try:
            raw = input(f"{message} ({hint}): ").strip().lower()
        except (EOFError, KeyboardInterrupt):
            print("\nSetup cancelled.")
            sys.exit(1)
        if not raw:
            return default
        if raw in ("y", "yes"):
            return True
        if raw in ("n", "no"):
            return False
        print("  Please answer y or n.")


def _prompt_secret(message: str) -> str:
    """Read a secret; fall back to visible input when getpass is unavailable."""
    try:
        import getpass

        while True:
            try:
                value = getpass.getpass(f"{message}: ").strip()
            except (EOFError, KeyboardInterrupt):
                print("\nSetup cancelled.")
                sys.exit(1)
            if value:
                return value
            print("  Please enter a value (or Ctrl+C to cancel).")
    except Exception:
        return _prompt(message)


def build_env_lines(answers: dict) -> list[str]:
    """Build .env file lines from wizard answers."""
    lines: list[str] = [
        "# Generated by scripts/setup.py",
        f"# {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
        "",
        "# --- Local MVP defaults (no GCP / Firebase required) ---",
    ]
    for key, value in MVP_DEFAULTS.items():
        lines.append(f"{key}={value}")

    provider = answers.get("llm_provider", "gemini")
    lines.extend(
        [
            "",
            "# --- LLM (required) ---",
            f"LLM_MODEL={answers.get('llm_model', LLM_MODELS[provider])}",
        ]
    )
    if provider == "openai":
        lines.append(f"OPENAI_API_KEY={answers['openai_api_key']}")
    else:
        lines.append(f"GEMINI_API_KEY={answers['gemini_api_key']}")

    optional_sections: list[tuple[str, list[str]]] = []

    if answers.get("enable_github"):
        optional_sections.append(
            (
                "GitHub (CTO agent — PR review, autofix)",
                [f"GITHUB_TOKEN={answers['github_token']}"],
            )
        )

    if answers.get("enable_jira"):
        optional_sections.append(
            (
                "Jira (Product agent — release notes, board automation)",
                [
                    f"JIRA_BASE_URL={answers['jira_base_url']}",
                    f"JIRA_EMAIL={answers['jira_email']}",
                    f"JIRA_API_TOKEN={answers['jira_api_token']}",
                    f"JIRA_PROJECT_KEY={answers['jira_project_key']}",
                    f"JIRA_AUTOMATION_WEBHOOK_SECRET={answers.get('jira_webhook_secret', 'change-me-local-dev')}",
                ],
            )
        )

    if answers.get("enable_discord"):
        discord_lines = []
        if answers.get("discord_marketing"):
            discord_lines.append(f"DISCORD_WEBHOOK_URL_MARKETING={answers['discord_marketing']}")
        if answers.get("discord_product"):
            discord_lines.append(f"DISCORD_WEBHOOK_URL_PRODUCT={answers['discord_product']}")
        if answers.get("discord_cto"):
            discord_lines.append(f"DISCORD_WEBHOOK_URL_CTO={answers['discord_cto']}")
        if discord_lines:
            optional_sections.append(("Discord (notifications)", discord_lines))

    if answers.get("enable_ga4"):
        optional_sections.append(
            (
                "Google Analytics 4 (Marketing agent)",
                [
                    f"GOOGLE_PROJECT_ID={answers['google_project_id']}",
                    f"GA4_PROPERTY_ID={answers['ga4_property_id']}",
                    f"GOOGLE_SERVICE_ACCOUNT_EMAIL={answers.get('google_service_account_email', '')}",
                ],
            )
        )

    if answers.get("enable_cursor"):
        optional_sections.append(
            (
                "Cursor (CTO autofix via cloud agents)",
                [f"CURSOR_API_KEY={answers['cursor_api_key']}"],
            )
        )

    for title, section_lines in optional_sections:
        lines.extend(["", f"# --- {title} ---", *section_lines])

    lines.extend(
        [
            "",
            "# --- Optional: add more integrations from env.example ---",
            "# cp env.example .env.full && merge any keys you need",
            "",
        ]
    )
    return lines


def write_env_file(path: str, lines: list[str], overwrite: bool) -> None:
    if os.path.exists(path) and not overwrite:
        raise FileExistsError(path)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
        if not lines[-1].endswith("\n"):
            fh.write("\n")


def run_wizard() -> dict:
    print()
    print("=" * 60)
    print("  Bigas setup — local MVP in under 5 minutes")
    print("=" * 60)
    print()
    print("This wizard creates a minimal .env for local evaluation:")
    print("  • In-memory chat (no Firebase)")
    print("  • Dev login (any email + bigas-dev-token)")
    print("  • Only the LLM API key is required")
    print()

    if os.path.exists(ENV_PATH):
        if not _prompt_yes_no(f"{ENV_PATH} already exists. Overwrite?", default=False):
            print("Keeping existing .env — nothing changed.")
            sys.exit(0)

    print("\n--- Step 1: LLM provider (required) ---")
    provider = _prompt("Provider: gemini or openai", "gemini").lower()
    if provider not in LLM_MODELS:
        print(f"  Unknown provider '{provider}', using gemini.")
        provider = "gemini"

    answers: dict = {"llm_provider": provider}
    if provider == "openai":
        answers["openai_api_key"] = _prompt_secret("OpenAI API key")
    else:
        answers["gemini_api_key"] = _prompt_secret("Gemini API key")

    custom_model = _prompt("LLM model (leave default to skip)", LLM_MODELS[provider])
    if custom_model != LLM_MODELS[provider]:
        answers["llm_model"] = custom_model

    print("\n--- Step 2: Optional specialists ---")
    print("Enable only what you need — you can re-run this script anytime.\n")

    if _prompt_yes_no("Enable CTO agent? (GitHub PR review)", default=False):
        answers["enable_github"] = True
        answers["github_token"] = _prompt_secret("GitHub personal access token (repo scope)")

    if _prompt_yes_no("Enable Product agent? (Jira release notes & automation)", default=False):
        answers["enable_jira"] = True
        answers["jira_base_url"] = _prompt("Jira base URL (e.g. https://yourco.atlassian.net)")
        answers["jira_email"] = _prompt("Jira account email")
        answers["jira_api_token"] = _prompt_secret("Jira API token")
        answers["jira_project_key"] = _prompt("Jira project key (e.g. BIG)")

    if _prompt_yes_no("Enable Marketing agent? (GA4 analytics)", default=False):
        answers["enable_ga4"] = True
        answers["google_project_id"] = _prompt("Google Cloud project ID")
        answers["ga4_property_id"] = _prompt("GA4 property ID (numeric)")
        answers["google_service_account_email"] = _prompt(
            "Service account email (for GA4 API)", ""
        )

    if _prompt_yes_no("Send reports to Discord?", default=False):
        answers["enable_discord"] = True
        if _prompt_yes_no("  Marketing Discord webhook?", default=True):
            answers["discord_marketing"] = _prompt_secret("  DISCORD_WEBHOOK_URL_MARKETING")
        if _prompt_yes_no("  Product Discord webhook?", default=False):
            answers["discord_product"] = _prompt_secret("  DISCORD_WEBHOOK_URL_PRODUCT")
        if _prompt_yes_no("  CTO Discord webhook?", default=False):
            answers["discord_cto"] = _prompt_secret("  DISCORD_WEBHOOK_URL_CTO")

    if answers.get("enable_github") and _prompt_yes_no(
        "Enable Cursor autofix for failed PRs?", default=False
    ):
        answers["enable_cursor"] = True
        answers["cursor_api_key"] = _prompt_secret("Cursor API key")

    return answers


def main() -> None:
    answers = run_wizard()
    lines = build_env_lines(answers)
    write_env_file(ENV_PATH, lines, overwrite=True)

    print()
    print("=" * 60)
    print(f"  Wrote {ENV_PATH}")
    print("=" * 60)
    print()
    print("Next steps:")
    print("  1. docker compose up --build")
    print("     # or: python run_core.py  (after pip install -r requirements.txt)")
    print("  2. Open http://localhost:8080")
    print("  3. Sign in with any email and token: bigas-dev-token")
    print()
    print("Production deploy: see README → Tutorial: deploy your first Bigas server")
    print()


if __name__ == "__main__":
    main()
